[package]
name = "hard_flag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "^0.10.8"
aes = "^0.8.3"
linux-syscall = "^1.0.0"
clap = { version = "^4.4.6", features = ["derive"] }
